# Settings
settings:
  interval: 5 # in seconds
  log_path: logs/test.log # path to logfile

# ClickHouse credentials
clickhouse:
 db: metrics
 table: nginx
 host: localhost
 port: 8123
 credentials:
  user: default
  password:
 columns:
   RemoteAddr:
    var_name: remote_addr
    var_type: string
   RemoteUser:
    var_name: remote_user
    var_type: string
   TimeLocal:
    var_name: time_local
    var_type: datetime
   Request:
    var_name: request
    var_type: string
   RequestTime:
    var_name: request
    var_type: float
   Status:
    var_name: status
    var_type: integer
   BytesSent:
    var_name: bytes_sent
    var_type: integer
   HttpReferer:
    var_name: http_referer
    var_type: string
   HttpUserAgent:
    var_name: http_user_agent
    var_type: string

# NGINX
nginx:
  log_type: main
  log_format: $remote_addr - $remote_user [$time_local] "$request" $status $bytes_sent "$http_referer" "$http_user_agent"
